import requests
from typing import Dict, List, Any, Optional

class WebhookDispatcher:
    """
    Automated League Notification Hub:
    Dispatches rich embeds, weekly recaps, power rankings, and alerts
    directly to Discord and Slack league channels.
    """

    def send_broadcast(self, webhook_url: str, payload_type: str, data: Dict[str, Any], platform: str = "auto") -> Dict[str, Any]:
        """
        Sends formatted payload to Discord or Slack webhook.
        Detects platform automatically if set to 'auto'.
        """
        if not webhook_url or not webhook_url.strip():
            return {"status": "error", "message": "No webhook URL provided."}

        url = webhook_url.strip()
        is_slack = "hooks.slack.com" in url or platform.lower() == "slack"

        try:
            if is_slack:
                payload = self._build_slack_payload(payload_type, data)
            else:
                # Default Discord
                payload = self._build_discord_payload(payload_type, data)

            resp = requests.post(url, json=payload, headers={"Content-Type": "application/json"}, timeout=8)
            
            # Discord returns 204 No Content on success; Slack returns 200 OK with body 'ok'
            if resp.status_code in [200, 204]:
                return {
                    "status": "success",
                    "platform": "Slack" if is_slack else "Discord",
                    "status_code": resp.status_code,
                    "message": f"Successfully delivered {payload_type} broadcast to {('Slack' if is_slack else 'Discord')}!"
                }
            else:
                return {
                    "status": "error",
                    "status_code": resp.status_code,
                    "message": f"Webhook delivery returned error [{resp.status_code}]: {resp.text}"
                }
        except Exception as e:
            return {"status": "error", "message": f"Webhook transmission failed: {str(e)}"}

    def _build_discord_payload(self, payload_type: str, data: Dict[str, Any]) -> Dict[str, Any]:
        """Builds Discord rich embed payload."""
        if payload_type == "test_ping":
            return {
                "username": "Fantasy Sports Manager",
                "avatar_url": "https://img.icons8.com/color/96/football2.png",
                "embeds": [{
                    "title": "🏈 Fantasy Sports Manager Connection Verified!",
                    "description": "Your Discord webhook is configured and receiving live updates.",
                    "color": 0x4f46e5,
                    "fields": [
                        {"name": "Status", "value": "🟢 Online & Ready", "inline": True},
                        {"name": "Features Active", "value": "Newsletters • Power Rankings • Waiver Alerts", "inline": True}
                    ],
                    "footer": {"text": "AI & Graph-Powered Fantasy Command Center"}
                }]
            }

        if payload_type == "newsletter":
            headline = data.get("headline", "Weekly League Dispatch")
            editorial = data.get("editorial", "")
            league_name = data.get("league_name", "Fantasy League")
            week = data.get("week", 1)

            fields = []
            awards = data.get("awards", [])
            for a in awards[:4]:
                fields.append({
                    "name": f"{a.get('icon', '🏆')} {a.get('title')}",
                    "value": f"**{a.get('recipient')}** ({a.get('team')})\n*{a.get('blurb')}*",
                    "inline": False
                })

            lookahead = data.get("lookahead", {})
            if lookahead:
                fields.append({
                    "name": "🔮 Next Week's Game of the Week",
                    "value": f"**{lookahead.get('game_of_the_week')}**\n{lookahead.get('hype_text')}",
                    "inline": False
                })

            return {
                "username": f"{league_name} Commish Bot",
                "avatar_url": "https://img.icons8.com/color/96/trophy.png",
                "embeds": [{
                    "title": headline,
                    "description": editorial[:2000],
                    "color": 0x10b981,
                    "fields": fields,
                    "footer": {"text": f"Week {week} Official Dispatch • Generated by AI Commish"}
                }]
            }

        if payload_type == "power_rankings":
            league_name = data.get("league_name", "Fantasy League")
            rankings = data.get("rankings", [])
            
            ranking_lines = []
            for idx, r in enumerate(rankings[:10], start=1):
                ranking_lines.append(
                    f"`#{idx:02d}` **{r.get('team', 'Team')}** ({r.get('manager', 'Manager')}) • "
                    f"All-Play: `{r.get('all_play_record', '0-0')}` • Score: `{r.get('power_score', 0)}`"
                )

            return {
                "username": "Power Rankings Oracle",
                "avatar_url": "https://img.icons8.com/color/96/chart.png",
                "embeds": [{
                    "title": f"📊 True Power Rankings & All-Play Standings • {league_name}",
                    "description": "\n".join(ranking_lines) if ranking_lines else "No rankings available.",
                    "color": 0x6366f1,
                    "footer": {"text": "Computed using True All-Play & Coaching Efficiency"}
                }]
            }

        # Generic fallback
        return {
            "username": "Fantasy Sports Manager",
            "content": f"📢 **Update from Fantasy Sports Manager**: {data.get('message', 'New league notification')}"
        }

    def _build_slack_payload(self, payload_type: str, data: Dict[str, Any]) -> Dict[str, Any]:
        """Builds Slack Block Kit payload."""
        if payload_type == "test_ping":
            return {
                "text": "🏈 Fantasy Sports Manager Connection Verified!",
                "blocks": [
                    {
                        "type": "header",
                        "text": {"type": "plain_text", "text": "🏈 Fantasy Sports Manager Connection Verified!"}
                    },
                    {
                        "type": "section",
                        "text": {"type": "mrkdwn", "text": "Your Slack webhook is verified and receiving automated league dispatches."}
                    }
                ]
            }

        headline = data.get("headline", "Weekly League Dispatch")
        editorial = data.get("editorial", "")
        
        blocks = [
            {
                "type": "header",
                "text": {"type": "plain_text", "text": f"🏈 {headline[:140]}"}
            },
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": f"> {editorial}"}
            },
            {"type": "divider"}
        ]

        awards = data.get("awards", [])
        for a in awards[:3]:
            blocks.append({
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*{a.get('icon')} {a.get('title')}*\n*{a.get('recipient')}* ({a.get('team')})\n_{a.get('blurb')}_"
                }
            })

        return {
            "text": headline,
            "blocks": blocks
        }

webhook_dispatcher = WebhookDispatcher()
